from enum import Enum


class Repo(str, Enum):
    BASEOS = "BASEOS"
    APPSTREAM = "APPSTREAM"
    POWERTOOLS = "POWERTOOLS"
    EXTERNAL = "EXTERNAL"
    MODULAR_CANDIDATE = "MODULAR_CANDIDATE"
    ORIGINAL = "ORIGINAL"
    INFRA = "INFRA"


class BuildStatus(str, Enum):
    QUEUED = "QUEUED"
    BUILDING = "BUILDING"
    FAILED = "FAILED"
    SUCCEEDED = "SUCCEEDED"
    CANCELLED = "CANCELLED"


class ImportStatus(str, Enum):
    QUEUED = "QUEUED"
    IN_PROGRESS = "IN_PROGRESS"
    FAILED = "FAILED"
    SUCCEEDED = "SUCCEEDED"
    CANCELLED = "CANCELLED"
